services:
  keycloak:
    build:
      context: ./keycloak-email-verify-listener
      dockerfile: Dockerfile
    image: ${CI_REGISTRY_IMAGE}/keycloak-email-verify-listener:latest
    ports:
      - "8080:8080"
    environment:
# Đã có sẵn realm master trong DB do trc đó đã tạo r nên k cần chỗ này nữa
#     KC_BOOTSTRAP_ADMIN_USERNAME: admin
#     KC_BOOTSTRAP_ADMIN_PASSWORD: 26102004
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://192.168.21.141:5432/keycloak"
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: "26102004"

      KC_SPI_EVENTS_LISTENER__KEYCLOAK_TO_RABBITMQ__HOST: 192.168.21.128
      KC_SPI_EVENTS_LISTENER__KEYCLOAK_TO_RABBITMQ__PORT: "5672"
      KC_SPI_EVENTS_LISTENER__KEYCLOAK_TO_RABBITMQ__USERNAME: admin
      KC_SPI_EVENTS_LISTENER__KEYCLOAK_TO_RABBITMQ__PASSWORD: 26102004
      KC_SPI_EVENTS_LISTENER__KEYCLOAK_TO_RABBITMQ__VIRTUAL_HOST: sgstore
      KC_SPI_EVENTS_LISTENER__KEYCLOAK_TO_RABBITMQ__EXCHANGE: user.events
      KC_SPI_EVENTS_LISTENER__KEYCLOAK_TO_RABBITMQ__ROUTING_KEY: user.email.verified
    networks:
      - sgstore-network-02

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.3.1
    environment:
      - node.name=es01
      - cluster.name=es-single-node
      - discovery.type=single-node
      - ELASTIC_PASSWORD=26102004
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - /home/ubuntu/esdata:/usr/share/elasticsearch/data
    networks:
      - sgstore-network-02

networks:
  sgstore-network-02:
    driver: bridge