services:
  consul-client:
    image: hashicorp/consul:1.22.3
    command: [ "agent", "-config-dir=/consul/config-ro" ]
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
    networks:
      - sgstore-network-01
    volumes:
      - /etc/consul.d:/consul/config-ro:ro

  common:
    build:
      context: .
      dockerfile: common/Dockerfile

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: ${CI_REGISTRY_IMAGE}/user-service:latest
    ports:
      - "8082:8082"
    networks:
      - sgstore-network-01
    environment:
      SPRING_PROFILES_ACTIVE: dev,keycloak,postgres,rabbit
#    volumes:
#      - ./configs/user-service:/configs:ro
    depends_on:
      - consul-client

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    image: ${CI_REGISTRY_IMAGE}/product-service:latest
    ports:
      - "8081:8081"
    networks:
      - sgstore-network-01
    environment:
      SPRING_PROFILES_ACTIVE: dev,postgres,rabbit
      APP_IMAGE_UPLOAD_DIR: /home/ubuntu/sgstore/images
    volumes:
      - /home/ubuntu/sgstore/images:/home/ubuntu/sgstore/images
#      - ./configs/product-service:/configs:ro
    depends_on:
      - consul-client

  catalog-service:
    build:
      context: .
      dockerfile: catalog-service/Dockerfile
    image: ${CI_REGISTRY_IMAGE}/catalog-service:latest
    ports:
      - "8083:8083"
    networks:
      - sgstore-network-01
    environment:
      SPRING_PROFILES_ACTIVE: dev,postgres,rabbit,elastic
      APP_IMAGE_UPLOAD_DIR: /home/ubuntu/sgstore/images
    volumes:
      - /home/ubuntu/sgstore/images:/home/ubuntu/sgstore/images:ro
#      - ./configs/catalog-service:/configs:ro
    depends_on:
      - consul-client

  cart-service:
    build:
      context: .
      dockerfile: cart-service/Dockerfile
    image: ${CI_REGISTRY_IMAGE}/cart-service:latest
    ports:
      - "8084:8084"
    networks:
      - sgstore-network-01
    environment:
      SPRING_PROFILES_ACTIVE: dev,postgres,rabbit
      #    volumes:
      #      - ./configs/catalog-service:/configs:ro
    depends_on:
      - consul-client

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    image: ${CI_REGISTRY_IMAGE}/payment-service:latest
    ports:
      - "8085:8085"
    networks:
      - sgstore-network-01
    environment:
      SPRING_PROFILES_ACTIVE: dev,postgres,rabbit
    depends_on:
      - consul-client

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    image: ${CI_REGISTRY_IMAGE}/order-service:latest
    ports:
      - "8086:8086"
    networks:
      - sgstore-network-01
    environment:
      SPRING_PROFILES_ACTIVE: dev,postgres,rabbit
    depends_on:
      - consul-client


networks:
  sgstore-network-01:
    driver: bridge


