SERVER_PORT: 8084
# Database
DB_URL: jdbc:postgresql://192.168.21.141:5432/sgstore
DB_USERNAME: postgres
DB_PASSWORD: 26102004
DB_DDL: update

#RabbitMQ
RABBITMQ_HOST: 192.168.21.128
RABBITMQ_PORT: 5672
RABBITMQ_USERNAME: admin
RABBITMQ_PASSWORD: 26102004
RABBITMQ_VHOST: sgstore

PRODUCT_VARIANT_QUERY_QUEUE_NAME: product.variant.query.q
PRODUCT_VARIANT_QUERY_EXCHANGE: product.events
PRODUCT_VARIANT_QUERY_ROUTING_KEY: product.variant.query

CART_QUERY_QUEUE_NAME: cart.query.q
CART_QUERY_EXCHANGE: cart.events
CART_QUERY_ROUTING_KEY: cart.query

CART_CLEAR_QUEUE_NAME: cart.clear.q
CART_CLEAR_EXCHANGE: cart.events
CART_CLEAR_ROUTING_KEY: cart.clear
