SERVER_PORT: 8085
# Database
DB_URL: jdbc:postgresql://192.168.21.141:5432/sgstore
DB_USERNAME: postgres
DB_PASSWORD: 26102004
DB_DDL: update

#RabbitMQ
RABBITMQ_HOST: 192.168.21.128
RABBITMQ_PORT: 5672
RABBITMQ_USERNAME: admin
RABBITMQ_PASSWORD: 26102004
RABBITMQ_VHOST: sgstore

PAYMENT_COMPLETED_QUEUE_NAME: payment.completed.q
PAYMENT_COMPLETED_EXCHANGE: payment.events
PAYMENT_COMPLETED_ROUTING_KEY: payment.completed
