SERVER_PORT: 8082
# Database
DB_URL: jdbc:postgresql://192.168.21.141:5432/sgstore
DB_USERNAME: postgres
DB_PASSWORD: 26102004
DB_DDL: update

#RabbitMQ
RABBITMQ_HOST: 192.168.21.128
RABBITMQ_PORT: 5672
RABBITMQ_USERNAME: admin
RABBITMQ_PASSWORD: 26102004
RABBITMQ_VHOST: sgstore

MARK_VERIFIED_QUEUE_NAME: user.email.verified.q
MARK_VERIFIED_EXCHANGE: user.events
MARK_VERIFIED_ROUTING_KEY: user.email.verified

#keycloak
KC_SERVER_URL: http://192.168.21.141:8080
KC_REALM: sgstore
KC_ADMIN_REALM: master
KC_CLIENT_ID: admin-cli
KC_ADMIN_USERNAME: admin
KC_ADMIN_PASSWORD: 26102004

